[package]
name = "hell"
description = "Lightweight wrapper around pipenv for running the Hellbox toolchain"
version = "0.1.4"
authors = ["Jack Jennings <jack@standard-library.com>"]
edition = "2018"

[dependencies]
clap = "2"
ansi_term = "*"